spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/testdb
      # 또는 jdbc:h2:tcp://localhost:9092/./data/testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: